routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');

Route::get('/post/{slug}', 'PostController@show');

Route::get('/get-columnists', 'PostController@getColumnists');

Route::get('/category/{code}', 'PostController@index');

Route::get('/tags/{name}', 'TagController@index');

Route::get('/search', 'PostController@search');

Route::post('/newsletter', 'HomeController@newsletter')->name('newsletter');

Route::get('/phpinfo', function(){echo phpinfo();});

Route::get('/rules', function () {
    return view('rules');
});

Route::get('/page/rules', function () {
    return redirect('/rules', 302);
});

Route::get('/contacts', function () {
    return view('contacts');
});

Route::get('/page/contacts', function () {
    return redirect('/contacts', 302);
});

Auth::routes();

Route::get('/home', function () {
    return redirect('/', 302);
})->name('home');

Route::get('/magazine/subject/{code}', function ($code) {
    if ($code === 'novosti') {
        return redirect('/', 302);
    }

    return redirect('/category/' . $code, 302);
});

Route::get('/magazine', function () {
    return redirect('/', 302);
});

Route::get('/magazine/category/{code}', function ($code) {
    if ($code === 'zdorovye-privychki') {
        $code = 'krasota-i-zdorove';
    }

    return redirect('/category/' . $code, 302);
});

Route::get('/get-galleries', 'GalleryController@get');

app/Post.php
<?php

namespace App;

use Encore\Admin\Facades\Admin;
use Illuminate\Database\Eloquent\Model;
use CyrildeWit\EloquentViewable\InteractsWithViews;
use CyrildeWit\EloquentViewable\Contracts\Viewable;
use Jenssegers\Date\Date;

class Post extends Model implements Viewable
{
    use InteractsWithViews;

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class, 'post_tag');
    }

    public function tile()
    {
        return $this->hasOne(Tile::class);
    }

    public function getCreatedAttribute(): string
    {
        return Date::createFromTimestamp(strtotime($this->created_at))->format('j F');
    }

    public function getCategoryNameAttribute()
    {
        return $this->category() && $this->category()->count() > 0 ? $this->category()->first()->name : '';
    }

    public function getColorAttribute()
    {
        return $this->category() && $this->category()->count() > 0 ? $this->category()->first()->color : '';
    }

    public function getYoutubeAttribute()
    {
        $regex = "#(?<=v=)[a-zA-Z0-9-]+(?=&)|(?<=v\/)[^&\n]+(?=\?)|(?<=v=)[^&\n]+|(?<=youtu.be/)[^&\n]+#";
        preg_match($regex, $this->link, $matches);

        return $matches[0] ?? '';
    }

    public function user()
    {
        return $this->belongsTo(\Encore\Admin\Auth\Database\Administrator::class, 'user_id', 'id');
    }

    public function getAuthorAttribute()
    {
        return $this->user->name ?? 'Неизвестен';
    }

    public function getViewsAttribute()
    {
        return views($this)->count() + $this->view_count;
    }

    public function getBackgroundImageAttribute()
    {
        return $this->category->img ?? 'images/1520х289 (10).jpg';
    }

    public function getBreadcrumbsAttribute()
    {
        return '<div class="breadcrumb">
            <a href="/">Главная</a>&nbsp;/&nbsp;
            <a href="/category/' . $this->category->code . '">' . $this->categoryName . '</a>&nbsp;/&nbsp;
            <a href="javascript:void(0);">' . $this->title . '</a>
        </div>';
    }

    public function getSimilarAttribute()
    {
        return Post::query()->whereHas('category', function ($q) {
            return $q->where('code', $this->category->code);
        })
            ->where('id', '!=', $this->id)
            ->take(3)
            ->get();
    }

    public function getImgAttribute($img)
    {
        if (file_exists(storage_path('app/public') . '/media/post/' . $img) ||
            file_exists(storage_path('app/public') . '/media/images/' . $img) ||
            file_exists(storage_path('app/public') . '/images/' . $img) ||
            file_exists(storage_path('app/public') . '/assets1/' . $img)) {
            return $img;
        }

        $exploded = explode(".", $img);
        $ext      = strtolower(end($exploded));
        array_pop($exploded);

        if (count($exploded) > 1) {
            $img = implode(".", $exploded);
        } else {
            $img = $exploded[0];
        }

        return $img . "." . $ext ?? '../img/post/default-post.png';
    }

    public function getIsKzAttribute()
    {
        $letters = [
            'ә',
            'і',
            'ң',
            'ү',
            'ұ',
            'қ',
            'ө',
            'һ',
        ];
        $case    = mb_str_split($this->title);

        foreach ($case as $letter) {
            if (in_array($letter, $letters, true)) {
                return true;
            }
        }

        return false;
    }

    public function getTitleHtmlAttribute()
    {
        if (mb_strlen($this->title) >= 50) {
            $this->title = mb_substr($this->title, 0, 50) . ' ...';
        }

        return $this->title;
    }
}

app/Http/Controllers/PostController.php
<?php
namespace App\Http\Controllers;

use App\Category;
use App\Post;
use Illuminate\Http\Request;

class PostController
{
    public function show(Request $request)
    {
        $post      = Post::query()->where('slug', $request->slug)->first();
        $expiresAt = now()->addMinutes(30);

        views($post)->cooldown($expiresAt)->record();

        return view('posts.show', compact(['post']));
    }

    public function getColumnists(Request $request)
    {
        $columnists = Post::query()
            ->where('is_columnist', 1)
            ->orderBy('id', 'asc')
            ->offset($request->get('count'))
            ->limit(2)
            ->get();

        return response()->json([
            'status' => 'ok',
            'html'   => view('ajax.columnists', ['columnists' => $columnists])->render()
        ]);
    }

    public function index(Request $request)
    {
        $code  = preg_replace('/[^a-z0-9-]/', '', $request->route('code'));
        $posts = collect();

        if ($code === 'semija-i-deti') {
            $ids = [
                4,
                79,
                10,
                14,
            ];
            $categoryName = 'Семья и дети';
        } elseif($code === 'krasota-i-zdorove') {
            $ids = [
                52,
                53
            ];
            $categoryName = 'Красота и здоровье';
        } elseif($code === 'nastojashhie-istorii') {
            $ids = [
                107
            ];
            $categoryName = 'Настоящие истории';
        } elseif($code === 'moda-i-stil') {
            $ids = [
                39,
                54,
                49,
                36,
            ];

            $categoryName = 'Мода и стиль';
        } elseif($code === 'zvezdy') {
            $ids = [
                48,
                19,
                47,
                44,
                76,
            ];
            $categoryName = 'Звезды';
        } elseif($code === 'muzcina') {
            $ids = [
                3,
                18,
                65,
                56,
                60,
                37,
                81,
            ];
            $categoryName = 'Мужчина';
        }

        if (isset($ids)) {
            $categories = Category::query()->whereIn('id', $ids)->get();

            foreach ($categories as $category) {
                $posts = $posts->merge($category->posts()->where('approved', 1)->get());
            }

            $posts    = $posts->paginate(config('app.pagination.per_page'));
            $category = $categories->first();
            $category->name = $categoryName;
        } else {
            $category = Category::query()->where('code', $code)->first();
            $posts    = $category->posts()->where('approved', 1)->get()->paginate(config('app.pagination.per_page'));
        }

        if (!$category) {
            abort(404);
        }

        return view('posts.index', compact(['category', 'posts']));
    }


    public function search(Request $request)
    {
        $q = preg_replace("/[^A-Za-zА-Яа-я0-9 ?!,]/u", '', $request->get('query'));

        $posts = Post::query()
            ->where('approved', 1)
            ->where(function ($query) use ($q) {
                $query->where('title', 'like', '%' . $q . '%');
                $query->orWhere('body', 'like', '%' . $q . '%');
            })
            ->paginate(10);

        return view('search', compact('posts'));
    }
}

resources/views/posts/index.blade.php
@extends('layout.app')

@section('content')
    <div id="category" class="main-content">
        <h1 class="text-center">
            @if(isset($category))
                {{ $category->name }}
            @else
                #{{ $tag->name }}
            @endif
        </h1>
        <div class="container-fluid stylized-container">
            @if(isset($category))
                {!! $category->breadcrumbs !!}
            @endif
            <div class="row border-bottom pb-5 mb-3">
                @if($posts && $posts->count() > 0)
                    @foreach($posts as $post)
                        <div class="col-md-4 mb-3">
                            <div class="post shadow-sm">
                                <a href="/post/{{ $post->slug }}">
                                    <div class="post-img" style="background-image: url('/media/post/{{ $post->img }}')"></div>
                                </a>
                                <div class="post-details">
                                    <div class="post-label">{{ $post->categoryName }}</div>
                                    <a href="/post/{{ $post->slug }}"><div class="post-title">{{ $post->title }}</div></a>
                                    <div class="post-date">{{ $post->created }}
                                        <span class="views-count">{{ $post->views }}</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    @endforeach
                    <div class="col-md-12 text">
                        {{ $posts->links() }}
                    </div>
                @else
                    <div class="col-md-12">
                        <div class="text-center py-5 h5">
                            Нет статей по данной категории :(
                        </div>
                    </div>
                @endif
            </div>
        </div>
    </div>
@endsection

resources/views/posts/show.blade.php
@extends('layout.app')

@section('styles')
    <link rel="stylesheet" href="{{ asset('/css/slick.css') }}">
    <link rel="stylesheet" href="{{ asset('/css/slick-theme.css') }}">
    <link rel="stylesheet" href="{{ asset('/css/jssocials.css') }}">
    <link rel="stylesheet" href="{{ asset('/css/jssocials-theme-flat.css') }}">
    @if($post->isKz)
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">
        <style>
            .article-body p, .article-body a, .breadcrumb a {
                font-family: 'Roboto', sans-serif!important;
            }
        </style>
    @endif
@endsection

@section('content')
    <div class="container-fluid px-0 main-content">
        <div class="article-header py-3 pb-4 mb-3">
            <div class="article-bg" style="background-image:url('/storage/{{ $post->backgroundImage }}')"></div>
            <div class="container-fliuid stylized-container mx-auto px-0">
                <div class="row">
                    <div class="col-md-6">
                        <div class="article-categories">
                            <a href="/category/{{ $post->category->code }}">{{ $post->category->name }}</a>
                        </div>
                    </div>
                    <div class="col-md-6 text-md-right">
                        <div class="article-tags">
                            @foreach($post->tags()->take(3)->get() as $tag)
                                <a href="/tags/{{ mb_strtolower($tag->name) }}">#{{ $tag->name }}</a>
                            @endforeach
                        </div>
                    </div>
                </div>
                <h1>{{ $post->title }}</h1>
                <div class="article-date">
                    {{ $post->created }}
                    <span class="views-count">{{ $post->views }}</span>
                </div>
                <div class="share-socials-white"></div>
            </div>
        </div>
    </div>
    <div class="container-fluid stylized-container bg-white p-4 pb-5" id="article">
        {!! $post->breadcrumbs !!}
        <div class="row">
            <div class="col-md-9">
                @if ($post->audio)
                <div class="article-audio mb-3">
                    <div class="article-audio-label">Слушать статью</div>
                </div>
                <audio controls>
                    <source src="/storage/{{ $post->audio }}">
                </audio>
                @endif
                <div class="article-body">
                    {!! $post->body !!}
                </div>
                <div class="share-socials-black"></div>
            </div>
            <div class="col-md-3">
                <div class="post-rklm mb-3">
                    <div>Реклама</div>
                </div>
                <div class="similar-posts">
                @foreach($post->similar as $similarPost)
                    <div class="post shadow-sm">
                        <a href="{{ $similarPost->slug }}">
                            <div class="post-img similar-post-img" style="background-image: url('/media/post/{{ $similarPost->img }}')"></div>
                        </a>
                        <div class="post-details">
                            <div class="post-label">{{ $similarPost->categoryName }}</div>
                            <a href="{{ $similarPost->slug }}"><div class="post-title">{{ $similarPost->title }}</div></a>
                            <div class="post-date">{{ $similarPost->created }}
                                <span class="views-count">{{ $similarPost->views }}</span>
                            </div>
                        </div>
                    </div>
                @endforeach
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid stylized-container newsletter my-0 mx-auto mb-5">
        <div class="row">
            <div class="col-md-8">
                <div class="newsletter-title">Подпишись и будь в курсе всего самого интересного на Comode.kz</div>
                <form action="{{ route('newsletter') }}" class="form-inline" id="newsletter">
                    <div class="form-group">
                        <input type="text" placeholder="Ваше имя" name="name" required>
                    </div>
                    <div class="form-group">
                        <input type="email" placeholder="Ваше email" name="email" required>
                    </div>
                    <button class="btn btn-blue">Подписаться</button>
                </form>
            </div>
            <div class="col-md-4"></div>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="{{ asset('/js/jssocials.min.js') }}"></script>
    <script src="{{ asset('/js/slick.min.js') }}"></script>
    <script>
        $(document).ready(function () {
            $(".share-socials-white").jsSocials({
                showLabel: false,
                shares: [{
                    share: "telegram",
                    logo: "/img/social/telegram-white.svg",
                }, {
                    share: "facebook",
                    logo: "/img/social/facebook-white.svg",
                }, {
                    share: "whatsapp",
                    logo: "/img/social/whatsapp-white.svg",
                }, {
                    share: "email",
                    logo: "/img/social/mail-white.svg",
                }, {
                    share: "twitter",
                    logo: "/img/social/twitter-white.svg",
                }]
            });

            $(".share-socials-black").jsSocials({
                showLabel: false,
                shares: [{
                    share: "telegram",
                    logo: "/img/social/telegram.svg",
                }, {
                    share: "facebook",
                    logo: "/img/social/facebook.svg",
                }, {
                    share: "whatsapp",
                    logo: "/img/social/whatsapp.svg",
                }, {
                    share: "email",
                    logo: "/img/social/mail.svg",
                }, {
                    share: "twitter",
                    logo: "/img/social/twitter.svg",
                }]
            });

            function processGalleries() {
                let ids = [];

                $('.gallery-placeholder').each(function () {
                    let id = parseInt($(this).attr('class').replace(/[^0-9]/gi,''));
                    ids.push(id);
                });

                $.ajax({
                    url: "/get-galleries",
                    data: {
                        ids: ids,
                    },
                    success (response) {
                        if (response['status'] === 'ok') {
                            let html = $(response['data']);
                            for (let i = 0; i < html.length; i++) {
                                let slider = $(html[i]);
                                $(".article-body").find('.__gallery__' + slider.data('id') + '__').html(slider);
                            }

                            $('.article-body').find('.slick-slider').slick({
                                slidesToShow: 1,
                                arrows: true,
                                dots: true,
                            });
                        }
                    }
                });
            }

            processGalleries();

            $('.article-body').find('img').each(function (i) {
                let k = $(this).outerWidth() / $(this).outerHeight();

                if ($(window).outerWidth() < 768 || k >= 1.7) {
                    $(this).css({
                        'width': '100%',
                        'height': 'initial'
                    });
                    const $elem = $(this);
                    $elem[0].style.setProperty('height', 'initial', 'important');
                }
            });
        });
    </script>
@endsection